name: Landing PAGE quinto B

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Construir imagen de docker
        run: |
          docker build -t ghcr.io/andernarvaez05/flask-app:${{ github.sha }} .

      - name: Login en GitHub Container Registry
        run: |
          echo "${{ secrets.TOKENXD }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publicar la imagen creada
        run: |
          docker push ghcr.io/andernarvaez05/flask-app:${{ github.sha }}

      - name: Mostrar variables o secrets
        run: |
          echo "Probando servidor SSH"
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "User: ${{ secrets.VPS_USER }}"
          echo "Port: ${{ secrets.VPS_SSH_PORT }}"

      - name: Probar en Github container (SSH deploy)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Conexion SSH exitosa"
            touch ejemplo.txt

      - name: probar conexiones scp
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "stack.yml,Makefile"
          target: "/home/${{ secrets.VPS_USER }}/landingb"

      - name: Desplegando servicios
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          envs: GITHUB_SHA
          script: |
            echo "Desplegando servicios"
            cd ~/landingb
            docker pull ghcr.io/andernarvaez05/flask-app:$GITHUB_SHA
            docker service update --image ghcr.io/andernarvaez05/flask-app:$GITHUB_SHA borrar_anderson